#Vehicle params

mass: 2.3 #from sim can be a bit off
g: 9.81

#moments of inertia 
Ixx: 0.075032 
Iyy: 0.075032
Izz: 0.15006

T: 0.02 #freq 50hz
# correlation matrix of the model
Q: 0.05
Qz: 5  #for the z axis that is a bit worse than the rest


number_of_sensors: 2
Sensor_prefix: [front,back,mid]
#front
front_R: [0.05, 0.05, 0.05] # correlation matrix of the sensor
front_odom: 0
front_topic: /uav/odometry2

#back
back_R: [0.1, 0.1, 0.1] # correlation matrix of the sensor
back_odom: 0
back_topic: /uav/odometry3
#mid
mid_R: [0.01, 0.01, 0.01] # correlation matrix of the sensor
mid_odom: 0
mid_topic: /uav/odometry4