#Vehicle params

initial_state: [0,0,0,0,0,0,0,0,0,0,0,0]
mass: 2.33 #from sim can be a bit off
g: 9.81

b: 0.000005 #0.00001819 #thrust
d: 0.0000806428 #drag
l: 0.314 #arm length

#moments of inertia
Ixx: 0.075032
Iyy: 0.075032
Izz: 0.15006

T: 0.02 #freq 25hz
# correlation matrix of the model
Q: 0.001 #0.005
Qz: 1  #for the z axis that is a bit worse than the rest


number_of_sensors: 2
Sensor_prefix: [front,back]
#front
front_R: [0.0025, 0.0025, 0.0025] # correlation matrix of the sensor
front_odom: 0
front_topic: /uav/odometry2

#back
back_R: [0.0049, 0.0049, 0.0049] # correlation matrix of the sensor
back_odom: 0
back_topic: /uav/odometry3
#mid
# mid_R: [0.01, 0.01, 0.01] # correlation matrix of the sensor
# mid_odom: 0
# mid_topic: /uav/odometry4
