estimation_frequency: 100
expected_imu_dt: 0.02

Q_acc_x: 0.0001
Q_acc_y: 0.0001
Q_acc_z: 0.0001
Q_angular_x: 0.00001
Q_angular_y: 0.00001
Q_angular_z: 0.00001

pose_p_cov: 0.01
vel_p_cov: 0.001
angle_p_cov: 0.01

p_drift_p_cov: 0.0001
q_drift_p_cov: 0.0001

estimate_acc_bias: true
acc_bias_var: [ 0.001,0.001,0.001]
acc_bias_p_cov: 0.001

estimate_gyro_bias: true
gyro_bias_var: [ 0.001,0.001,0.001]
gyro_bias_p_cov: 0.001

estimate_gravity: true
g: [0,0,-10.34]
g_p_cov: 0.1

#position sensor params
Sensor_prefix: [camera, pozyx, carto]
initial_sensor: carto

#camera
camera_is_orientation_sensor: true
camera_is_velocity_sensor: false
camera_estimate_drift: true
camera_topic: camera/odom/sample
camera_msg_type: 0
camera_R_pose: [0.05, 0.05, 0.01]
camera_R_angle: [0.2, 0.2, 0.2]
camera_rotation: [1,0,0,0,1,0,0,0,1]
camera_translation: [0,0,0]
camera_origin_at_first_measurement: false
camera_position_outlier_lim: [10, 10, 10]
camera_orientation_outlier_lim: [0, 0, 0]

#pozyx
pozyx_R_pose: [1, 1, 3]
pozyx_R_angle: [0.01, 0.01, 0.01]
pozyx_is_orientation_sensor: false
pozyx_estimate_drift: false
pozyx_is_velocity_sensor: false
pozyx_topic: pozyx/measured
pozyx_msg_type: 1
pozyx_rotation: [0.0, -1.0, 0.0,1.0, 0.0, 0, 0, 0.0, 1.0]
pozyx_translation: [-4.048,3.654,0.176]
pozyx_origin_at_first_measurement: true
pozyx_position_outlier_lim: [1, 1, 2]
pozyx_orientation_outlier_lim: [0, 0, 0]

#carto
carto_R_pose: [0.5, 0.5, 1]
carto_R_angle: [0.5, 0.5, 0.5]
carto_is_orientation_sensor: true
carto_is_velocity_sensor: false
carto_estimate_drift: true
carto_topic: uav/cartographer/transform
carto_msg_type: 1
carto_rotation: [0.0, -1.0, 0.0, 1.0, 0.0, 0, 0, 0.0, 1.0]
carto_translation: [-4.048,3.654,0.176]
carto_origin_at_first_measurement: true
carto_position_outlier_lim: [10, 10, 10]
carto_orientation_outlier_lim: [0, 0, 0]